name: monster
favicon: null
layout_spectrum: 0.491358362371102
typography_spectrum: 0.4073723186738789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8973920787684619
  lightness: 0.02316818735562265
  saturation: 0.5048293557483703
  rhythmicContrast: 0.6147942999377847
purpose: []
